package com.opsat.subscribity.presentation.theme

import androidx.compose.ui.graphics.Color

// Light — violet (primary) + emerald/mint (secondary) + warm amber (tertiary)
val LightPrimary = Color(0xFF6E56CF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE9DEFF)
val LightOnPrimaryContainer = Color(0xFF271258)
val LightSecondary = Color(0xFF1DA97A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFC6F3DC)
val LightOnSecondaryContainer = Color(0xFF04402A)
val LightTertiary = Color(0xFFE8823C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCC0)
val LightOnTertiaryContainer = Color(0xFF532200)
val LightBackground = Color(0xFFFBF8FF)
val LightOnBackground = Color(0xFF1C1B20)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1C1B20)
val LightSurfaceVariant = Color(0xFFECE6F5)
val LightOnSurfaceVariant = Color(0xFF4A4458)

// Dark — same brand hues, tuned for a dark surface
val DarkPrimary = Color(0xFFC6B7FF)
val DarkOnPrimary = Color(0xFF38186B)
val DarkPrimaryContainer = Color(0xFF4F3897)
val DarkOnPrimaryContainer = Color(0xFFE9DEFF)
val DarkSecondary = Color(0xFF7FDBB0)
val DarkOnSecondary = Color(0xFF003A21)
val DarkSecondaryContainer = Color(0xFF04562F)
val DarkOnSecondaryContainer = Color(0xFFC6F3DC)
val DarkTertiary = Color(0xFFFFB68A)
val DarkOnTertiary = Color(0xFF5A2600)
val DarkTertiaryContainer = Color(0xFF7A3900)
val DarkOnTertiaryContainer = Color(0xFFFFDCC0)
val DarkBackground = Color(0xFF141218)
val DarkOnBackground = Color(0xFFE7E0EC)
val DarkSurface = Color(0xFF141218)
val DarkOnSurface = Color(0xFFE7E0EC)
val DarkSurfaceVariant = Color(0xFF2A2530)
val DarkOnSurfaceVariant = Color(0xFFCBC4D4)
